language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarcloud:
    organization: "marmer-github"
    token:
      secure: "qFEpZVd5B+DC3TC5Dox1SAF6zrhuMYyDRHyyqXOQqW46knpYwzsz5Qikd0QoKy0Mue65lhScYR3ManM9fF7W+8dgGDUbRgt+uxUsPwFN6hawESikYpjvGasCDwXqNQlJqE8ZrtHFnx/VrNqBaIojkuwLfHwGrwz4qa0rQc/NPhwm/JXZl1i6DqHx+hesE2NcuMycHK9fhEwRZz0HVgWPSzcxZ133Nyrj94ful12MckKL4xlJCQJQ5cKo3No6f+9gp77Vgu7Q04Eaq5rqVr9OZVcyGF1GnH3vCVFFlb8s0RXCHdeu/F9u2yC+U6viNLTfzyas/74sc4Cu29cRyFb7T78kVlK8ZQ28x76lGulin14xv5LM/Is2D25OXbvh5psbdcO64Cl512rLFALYqzpxP4qoRDrd3I3mTS2efasawPVwOIIM2baKYHxaU/f4u2XtQJOHud4CL4U2Xr/HjzQvgvzC5Ud7JbV7cJucct67laV+tBM+Re8SYIh6dH8o8Th8LNiUNGO9s8AYjcucsRXQiKUZJ12scl+nN6CchJoKP7O7i/8GW9cEXrqheW7C6+QSIPKeXy7j+55LcjEFOEZvptBXmgBMIgrfn0ZMS2mhC+CNZ6aQOiVotNOoux87M4xAmCT7pReI6KYLKqOjGlXXH1kosuZqP0sRTXZXnZleLlo="
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/apache-maven-${MAVEN_VERSION}"
  - "$HOME/.sonar/cache"
before_cache:
- rm -rfv $HOME/.m2/repository/io/github/marmer/protim
before_install:
- export M2_HOME=$HOME/apache-maven-${MAVEN_VERSION}
- if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
  | tar zxf - -C $HOME; fi
- export PATH=$M2_HOME/bin:$PATH
install:
- docker run -it --rm -v "$(pwd)":/opt/maven -w /opt/maven maven:3.5.0-jdk-8-alpine -v $HOME/.m2/repository:/root/.m2/repository/ mvn clean install -DskipTests=true -Dmaven.javadoc.skip -Dmaven.source.skip -Dassembly.skipAssembly -B -V -U
script:
- docker run -it --rm -v "$(pwd)":/opt/maven -w /opt/maven maven:3.5.0-jdk-8-alpine -v $HOME/.m2/repository:/root/.m2/repository/ mvn test -Dmaven.javadoc.skip -Dmaven.source.skip -Dassembly.skipAssembly -V
after_success:
- docker run -it --rm -v "$(pwd)":/opt/maven -w /opt/maven maven:3.5.0-jdk-8-alpine -v $HOME/.m2/repository:/root/.m2/repository/ mvn jacoco:prepare-agent package sonar:sonar -Dmaven.javadoc.skip -Dmaven.source.skip -Dassembly.skipAssembly -V
