language: java
#  the folowing line is a temporary solution until travis supports the JDK10 and can be inlined after
#jdk: oraclejdk10
sudo: required
services:
- postgresql
#- docker
addons:
  postgresql: "9.6"
  apt:
    packages:
#  the folowing line is a temporary solution until travis supports the JDK10 and can be inlined after
#    - oracle-java10-installer
#    - docker-ce
  sonarcloud:
    organization: "marmer-github"
    token:
      secure: "qFEpZVd5B+DC3TC5Dox1SAF6zrhuMYyDRHyyqXOQqW46knpYwzsz5Qikd0QoKy0Mue65lhScYR3ManM9fF7W+8dgGDUbRgt+uxUsPwFN6hawESikYpjvGasCDwXqNQlJqE8ZrtHFnx/VrNqBaIojkuwLfHwGrwz4qa0rQc/NPhwm/JXZl1i6DqHx+hesE2NcuMycHK9fhEwRZz0HVgWPSzcxZ133Nyrj94ful12MckKL4xlJCQJQ5cKo3No6f+9gp77Vgu7Q04Eaq5rqVr9OZVcyGF1GnH3vCVFFlb8s0RXCHdeu/F9u2yC+U6viNLTfzyas/74sc4Cu29cRyFb7T78kVlK8ZQ28x76lGulin14xv5LM/Is2D25OXbvh5psbdcO64Cl512rLFALYqzpxP4qoRDrd3I3mTS2efasawPVwOIIM2baKYHxaU/f4u2XtQJOHud4CL4U2Xr/HjzQvgvzC5Ud7JbV7cJucct67laV+tBM+Re8SYIh6dH8o8Th8LNiUNGO9s8AYjcucsRXQiKUZJ12scl+nN6CchJoKP7O7i/8GW9cEXrqheW7C6+QSIPKeXy7j+55LcjEFOEZvptBXmgBMIgrfn0ZMS2mhC+CNZ6aQOiVotNOoux87M4xAmCT7pReI6KYLKqOjGlXXH1kosuZqP0sRTXZXnZleLlo="
env:
  global:
  - SPRING_DATASOURCE_USERNAME=protim_ci_user SPRING_DATASOURCE_PASSWORD=protim_ci_pw
  #  the folowing line is a temporary solution until travis supports the JDK10 and can be removed after
  - JDK='Oracle JDK 10'
  matrix:
  - SPRING_DATASOURCE_URL=jdbc:h2:file:~/protim_ci_db
  - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/protim_ci_db
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/apache-maven-${MAVEN_VERSION}"
  - /tmp/nodebin
  #  the folowing line is a temporary solution until travis supports the JDK10 and can be removed after
  - /home/travis/jdk-10.0.2
before_cache:
- rm -rfv $HOME/.m2/repository/io/github/marmer/protim
before_install:
#  the folowing line is a temporary solution until travis supports the JDK10 and can removed after
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- export M2_HOME=$HOME/apache-maven-${MAVEN_VERSION}
- if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
  | tar zxf - -C $HOME; fi
- export PATH=$M2_HOME/bin:$PATH

before_script:  
  - psql -c "CREATE DATABASE protim_ci_db;" -U postgres
  - psql -c "CREATE USER protim_ci_user WITH PASSWORD 'protim_ci_pw';" -U postgres
install:
- . ./install-jdk.sh -F 10 -L BCL
- mvn clean install -DskipTests=true -Dmaven.javadoc.skip -Dmaven.source.skip -Dassembly.skipAssembly -B -V -U -T 2.0C
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dmaven.javadoc.skip -Dmaven.source.skip -Dassembly.skipAssembly -V -U -T 2.0C
#TODO Sona erklären, dass typescript bla coverage gedöns ...
# ... alles nur geklaut
#  <profile>
#  <id>sonar</id>
#  <activation>
#  <activeByDefault>true</activeByDefault>
#  </activation>
#  <properties>
#  <sonar.host.url>
#  http://sonar.ci.scag
#  </sonar.host.url>
#  <sonar.sources>src/main/java,src/main/app/src</sonar.sources>
#  <sonar.language/>
#  <sonar.typescript.lcov.reportPaths>src/main/app/coverage/lcov.info</sonar.typescript.lcov.reportPaths>
#  </properties>
#  <build>
#  <plugins>
#  <plugin>
#  <groupId>org.jacoco</groupId>
#  <artifactId>jacoco-maven-plugin</artifactId>
#  <version>0.8.1</version>
#  <configuration>
#  <destFile>${sonar.jacoco.reportPath}</destFile>
#  <append>true</append>
#  </configuration>
#  <executions>
#  <execution>
#  <id>agent</id>
#  <goals>
#  <goal>prepare-agent</goal>
#  </goals>
#  </execution>
#  </executions>
#  </plugin>
#  </plugins>
#  </build>
#  </profile>

#---------

#  $JAVA_HOME_1_8/bin/java -jar ./tools/sonar-scanner/sonar-scanner-cli-3.1.0.1141.jar

#--------- sonar-project.properties

#  sonar.host.url=http://sonar.ci.scag
#
#  sonar.sourceEncoding=UTF-8
#  sonar.projectKey=isbj-redesign-commons-frontend:jotu
#  sonar.projectName=ISBJ Frontend Lib (Jotu)
#  sonar.projectVersion=1.0
#  sonar.sources=src
#  sonar.typescript.lcov.reportPaths=coverage/lcov.info