language: java
jdk: oraclejdk8
sudo: required
env:
  - DOCKER_COMPOSE_VERSION=1.16.1
services:
  - docker
addons:
  apt:
    packages:
    - oracle-java8-installer
  sonarcloud:
    organization: "marmer-github"
    token:
      secure: "qFEpZVd5B+DC3TC5Dox1SAF6zrhuMYyDRHyyqXOQqW46knpYwzsz5Qikd0QoKy0Mue65lhScYR3ManM9fF7W+8dgGDUbRgt+uxUsPwFN6hawESikYpjvGasCDwXqNQlJqE8ZrtHFnx/VrNqBaIojkuwLfHwGrwz4qa0rQc/NPhwm/JXZl1i6DqHx+hesE2NcuMycHK9fhEwRZz0HVgWPSzcxZ133Nyrj94ful12MckKL4xlJCQJQ5cKo3No6f+9gp77Vgu7Q04Eaq5rqVr9OZVcyGF1GnH3vCVFFlb8s0RXCHdeu/F9u2yC+U6viNLTfzyas/74sc4Cu29cRyFb7T78kVlK8ZQ28x76lGulin14xv5LM/Is2D25OXbvh5psbdcO64Cl512rLFALYqzpxP4qoRDrd3I3mTS2efasawPVwOIIM2baKYHxaU/f4u2XtQJOHud4CL4U2Xr/HjzQvgvzC5Ud7JbV7cJucct67laV+tBM+Re8SYIh6dH8o8Th8LNiUNGO9s8AYjcucsRXQiKUZJ12scl+nN6CchJoKP7O7i/8GW9cEXrqheW7C6+QSIPKeXy7j+55LcjEFOEZvptBXmgBMIgrfn0ZMS2mhC+CNZ6aQOiVotNOoux87M4xAmCT7pReI6KYLKqOjGlXXH1kosuZqP0sRTXZXnZleLlo="
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/apache-maven-${MAVEN_VERSION}"
  - /usr/local/bin/docker-compose
before_cache:
- rm -rfv $HOME/.m2/repository/io/github/marmer/protim
before_install:
- sudo rm /usr/local/bin/docker-compose
- if [ ! -f /usr/local/bin/docker-compose ]; then curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- export M2_HOME=$HOME/apache-maven-${MAVEN_VERSION}
- if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
  | tar zxf - -C $HOME; fi
- export PATH=$M2_HOME/bin:$PATH
install:
- mvn clean install -DskipTests=true -Dmaven.javadoc.skip -Dmaven.source.skip -Dassembly.skipAssembly -B -V -U
script:
- docker-compose -f docker-compose-travis.yml up --force-recreate --abort-on-container-exit
