version: '3.7'

services:
  maven:
    image: maven:3.5.4-jdk-10-slim
    volumes:
    - "$TEMP/nodebin:/tmp/nodebin"
    - "./:/usr/src/protim"
    - "$HOME/.m2:/root/.m2"
    environment:
    - SPRING_DATASOURCE_USERNAME=protim_ci_user
    - SPRING_DATASOURCE_PASSWORD=protim_ci_pw
    - SPRING_DATASOURCE_URL
    command: ./ci.sh
    working_dir: /usr/src/protim
    networks:
    - overlay

  db:
    image: postgres:11-alpine
    networks:
    - overlay
    environment:
      POSTGRES_USER: protim_ci_user
      POSTGRES_PASSWORD: protim_ci_pw
      POSTGRES_DB: protim_ci_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - data-volume:/var/lib/postgresql/data/pgdata

volumes:
  data-volume:

networks:
  overlay: