version: '3.3'

services:
  maven:
    image: maven:3.5.0-jdk-8
    container_name: maven
    volumes:
      - .:/opt/maven
    working_dir: /opt/maven
    command: mvn clean install
    links:
     - db
    
  db:
    image: postgres
    environment:
      POSTGRES_USER: protim
      POSTGRES_PASSWORD: example
      POSTGRES_DB: protim
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data/pgdata
    #ports:
      #- 5432:5432
      
volumes:
  data-volume: