version: '3.3'

services:
  maven:
    image: maven:3.5.4-jdk-10-slim
    volumes:
    - "$TEMP/nodebin:/tmp/nodebin"
    - "./:/usr/src/protim"
    - "$HOME/.m2:/root/.m2"
    environment:
    - SPRING_DATASOURCE_USERNAME=protim_user
    - SPRING_DATASOURCE_PASSWORD=protim_pw
    - SPRING_DATASOURCE_URL
    - SONAR_CLOUD_TOKEN
    command: ./ci.sh
    working_dir: /usr/src/protim
    networks:
    - pgconnection

  db:
    image: postgres:11-alpine
    networks:
    - pgconnection
    environment:
      POSTGRES_USER: protim_user
      POSTGRES_PASSWORD: protim_pw
      POSTGRES_DB: protim_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - protim-volume:/var/lib/postgresql/data/pgdata
    expose:
    - 5432

volumes:
  protim-volume:

networks:
  pgconnection: