spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/protim
    url: jdbc:h2:file:~/protim_db
    username: protim_user
    password: protim_pw
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
server:
  ssl:
    key-store: classpath:ssl/defaultKeystore.p12
    key-store-password: protimKey
    keyStoreType: PKCS12
    keyAlias: protim
    enabled: true
  port: 443
