spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/protim
    url: jdbc:h2:file:~/protim_db
    username: protim_user
    password: protim_pw
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

#security:
#  require-ssl: false
#  user:
#    name: protim
#    password: protim
#  basic:
#    path:
#    - /rest/**