spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/protim
    username: protim
    password: protim
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: validate