version: '3.3'
services:
  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_USER: protim
      POSTGRES_PASSWORD: protim
      POSTGRES_DB: protim
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-volume:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
      
volumes:
  data-volume: