spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/protim
    url: jdbc:h2:file:~/protim_db
    username: protim_user
    password: protim_pw
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /management
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: when_authorized
      roles: ADMIN
server:
  ssl:
    key-store: classpath:ssl/defaultKeystore.p12
    key-store-password: protimKey
    keyStoreType: PKCS12
    keyAlias: protim
    enabled: true
  port: 443
global:
  cors:
    config:
      allowed-origins:
      - https://marmer.online
      - http://marmer.online
      - https://marmer.github.io
      - http://marmer.github.io
      - https://localhost
      - http://localhost
      - http://localhost:3000
      allow-credentials: true
